<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [78]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    if len(A[0])!=len(B):
        print("Not possible")
    else:
        temp=[[0 for i in range(0,len(B[0]))] for j in range(0,len(A))]
        for i in range(0,len(A)):
            for j in range(0,len(B[0])):
                for k in range(0,len(B)):
                    temp[i][j]+=(A[i][k]*B[k][j])
                #temp[][j]=hold   
        return temp#multiplication_of_A_and_B
A   = [[1, 3 ,4],
             [2 ,5 ,7],
             [5 ,9 ,6]]
B   = [[1, 0 ,0],
             [0 ,1 ,0],
             [0 ,0, 1]]
matrix_mul(A, B)

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [6]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    temp=A.copy()
    total=0
    for i in A:
        total=total+i
    for i in range(0,len(A)):
        temp[i]=temp[i]/total
    cum_sum=0
    for i in range(0,len(A)):
        cum_sum=temp[i]+cum_sum
        temp[i]=cum_sum
    pick=uniform(0.0,1.0)
    for i in range(0,len(A)):
        if  pick<temp[i]:
            return A[i]
    # your code here for picking an element from with the probability propotional to its magnitude
    #.
    #.
    #.
   # return #selected_random_number

def sampling_based_on_magnitued():
    A=[0,1,2,3,12,15,76,88,22,6,15]
  
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)
sampling_based_on_magnitued()

88
76
88
15
88
76
88
76
12
88
76
88
88
88
15
76
76
88
22
88
76
22
88
15
12
76
22
76
15
15
88
76
88
88
88
88
22
88
3
76
88
88
6
88
76
88
76
88
88
22
88
76
76
88
12
76
76
22
76
76
88
76
76
76
12
88
22
76
76
12
15
76
88
22
6
88
76
88
76
88
12
88
76
88
15
15
76
22
15
22
76
88
88
76
76
88
76
15
76


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [9]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    String=re.sub('[^0-9]','',String)
    String=re.sub('[0-9]','#',String)
   
            
    return  String# modified string which is after replacing the # with digits
String= '#2a$#b%c%561#'
replace_digits(String)

'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [10]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):# sort both list based on marks
    for i in range(0,len(marks)-1):
        m=marks[i]
        for j in range(i+1,len(marks)):
            if m<marks[j]:
                m=marks[j]
                marks[i],marks[j]=marks[j],marks[i]
                students[i],students[j]=students[j],students[i]
    # write code for computing top top 5 students
    top_5_students =students[0:5],marks[0:5] # compute this
    # write code for computing top least 5 students
    least_5_students =students[-1:-6:-1],marks[-1:-6:-1] # compute this
    # write code for computing top least 5 students
    m=max(marks)-min(marks)
    per_25=m*0.25 #25th percentile
    per_75=m*0.75 #75th percentile
    l1,l2=[],[]
    for i,j in zip(marks[::-1],students[::-1]):
        if i>per_25 and i<per_75:# filtering the studnets based on marks
            l1.append(j)
            l2.append(i)
    students_within_25_and_75 = l1,l2# compute this
    
    return top_5_students, least_5_students, students_within_25_and_75



students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
l=[top_5_students, least_5_students, students_within_25_and_75]
print(f'{top_5_students}\n{least_5_students}\n{students_within_25_and_75}')

        

(['student8', 'student10', 'student2', 'student5', 'student7'], [98, 80, 78, 48, 47])
(['student3', 'student4', 'student9', 'student6', 'student1'], [12, 14, 35, 43, 45])
(['student9', 'student6', 'student1', 'student7', 'student5'], [35, 43, 45, 47, 48])


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [11]:
import math
def cos_distance(s,p):# cosine distance formula implementation
    temp=(s[0]*p[0] + s[1]*p[1])
    s_temp=math.sqrt((s[0]**2)+(s[1]**2))*math.sqrt((p[1]**2)+(p[0]**2))
    a=math.acos(temp/s_temp)
    return a    
    
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure
# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    l=[]
    for i in S:
        l.append(cos_distance(i,P))
    dist=l
    sdist=sorted(dist)
    relative_ind=[dist.index(i) for i in sdist]
    relative_points=[S[i] for i in relative_ind]
    return relative_points[:5]

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
for i in points:
    print(i) #print the returned values

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [12]:
import math,re

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    a,b,c=[float(i.strip()) for i in re.split('x|y',line) ]# breaking the string into required values
    r=[]
    g=[]
    for i in range(0,len(red)):
        di=(a*red[i][0]+b*red[i][1]+c)
        r.append(di)
    for j in range(0,len(blue)):
        di=(a*blue[i][0]+b*blue[i][1]+c)
        g.append(di)
    rd=all(i>0 for i in r)# check whether all of them are having same sign
    gd=all(i<0 for i in g)# check whether all of them are having same sign
    if rd and gd:
        return 'YES'
    else:
        return 'NO'
    # your code


Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [41]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    lst=string.split(',')
    for i in range(len(lst)):# find the first value and fill left side values
        if lst[i].isdigit():
            for j in range(i+1):
                lst[j]=int(lst[i])//(i+1)
            new_in=i
            new_val=int(lst[i])
            break
    for i in range(new_in+1,len(lst)):
        if lst[i].isdigit():
            temp=(new_val+int(lst[i]))//(i-new_in+1)
            for j in range(new_in, i+1):
                lst[j]=temp
            new_in=i
            new_val=int(lst[i])
    for i in range(new_in+1,len(lst)):
        if not lst[i].isdigit():
            count=lst.count('_')
            break
    temp1=new_val//(count+1)
    for i in range(new_in,len(lst)):
        lst[i]=temp1
    return lst
    
    
    
S=  "_,_,30,_,_,_,50,_,_"
#S= "80,_,_,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)# print above values)

[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [19]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    d={}# dict for storing conditional probability
    ds={}# dict for counting s value
    for f in F:# fill the all possbilities of conditonal probality of dict and s
        for s in S:
            d[f+s]=0 
            ds[s]=0
    for a in A:# increment the dict value for every key found
        d[a[0]+a[1]]=d[a[0]+a[1]]+1
        ds[a[1]]=ds[a[1]]+1
    for i in ['F1','F2','F3','F4','F5']:# print the output in required form
        for j in ['S1','S2','S3']:
            print(f'P(F=={i}|S=={j})={d[i+j]}/{ds[j]}',end=',  ')
        print('')
            
            
    # your code
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P(F==F1|S==S1)=1/4,  P(F==F1|S==S2)=1/3,  P(F==F1|S==S3)=0/3,  
P(F==F2|S==S1)=1/4,  P(F==F2|S==S2)=1/3,  P(F==F2|S==S3)=1/3,  
P(F==F3|S==S1)=0/4,  P(F==F3|S==S2)=1/3,  P(F==F3|S==S3)=1/3,  
P(F==F4|S==S1)=1/4,  P(F==F4|S==S2)=0/3,  P(F==F4|S==S3)=1/3,  
P(F==F5|S==S1)=1/4,  P(F==F5|S==S2)=0/3,  P(F==F5|S==S3)=0/3,  


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [20]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    a=0
    b=[]
    c=[]
    for i,j in zip(S1.split(),S2.split()):# split the sentence into words and compare them
        if i==j:
            a=a+1
        else:
            b.append(i)
            c.append(j)   
    
            
    # your code
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(f'{a}\n{b}\n{c}\n')

7
['first', 'F', '5']
['second', 'S', '3']



<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [21]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math

# you can free to change all these codes/structure
def compute_log_loss(A):
    n=(-1/len(A))
    f=lambda x,y : x*(math.log(y)/math.log(10))
    s=0
    for i in A:
        s=s+f(i[0],i[1])+f(1-i[0],1-i[1])
    loss=n*s
    # your code
    
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
